### ISSUE TITLE
Laravel 5.4 support?

### ISSUE THREAD

**Issue by pedrodevoto** [nikolajlovenhardt/laravel-google-ads#18] opened 2017-02-23 12:06 UTC
I'm getting the following error, which I guess is due to the dependencies' versions.

```
[InvalidArgumentException]                                                   
  Could not find package nikolajlovenhardt/laravel-google-ads at any version   
  for your minimum-stability (stable). Check the package spelling or your min  
  imum-stability 
```

Any plans on supporting 5.4 in the sort term?

**Comment by pedrodevoto** [comment] 2017-02-23 12:21
Installed adding this to _composer.json_

```json
{
  "minimum-stability": "dev",
}
```

**Comment by nikolajlovenhardt** [comment] 2017-02-23 12:26
Duplicate of https://github.com/nikolajlovenhardt/laravel-google-ads/issues/12

**Closed by nikolajlovenhardt** 2017-02-23 12:26 UTC
