### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by bakhtari** [nikolajlovenhardt/laravel-google-ads#16] opened 2017-01-30 08:56 UTC
Hi 
googleads-php-lib pack update to v24 but your package is old and v14
please update your code!
Ali

**Comment by nikolajlovenhardt** [comment] 2017-01-30 10:48
@bakhtari Moving from v14 to v24 is a huge update due to the implementation of namespaces etc. I'll update it in the nearest future. You are welcome to open a PR.

Closing - duplicate of https://github.com/nikolajlovenhardt/laravel-google-ads/issues/8

**Closed by nikolajlovenhardt** 2017-01-30 10:48 UTC
